server:
  port: 8080
spring:
  application:
    name: gateway-service
  cloud:
    discovery:
      enabled: true
    gateway:
      mvc:
        routes:
          - id: r1
            uri: lb://CUSTOMER-SERVICE
            predicates:
            - Path=/customers/**
          - id: r2
            uri: lb://INVENTORY-SERVICE
            predicates:
            - Path=/products/**
