spring.application.name=config-service
server.port=9999
spring.cloud.config.server.git.uri=https://github.com/othsoh/ecom-app_config-props
spring.cloud.discovery.enabled=true
spring.cloud.config.server.git.default-label=main
